name: flutteq_lints
version: 1.1.0
description: Lint rules for Dart and Flutter used internally at Softeq.
repository: https://github.com/Softeq/flutteq_lints
issue_tracker: https://github.com/Softeq/flutteq_lints/issues
homepage: https://github.com/Softeq/flutteq_lints
documentation: https://github.com/Softeq/flutteq_lints
topics: [lints, analyzer, analysis]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_lints: ^4.0.0
